/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Qualcomm Kona (SM8250) interconnect IDs
 */

#ifndef __DT_BINDINGS_INTERCONNECT_QCOM_KONA_H
#define __DT_BINDINGS_INTERCONNECT_QCOM_KONA_H

#define KONA_ICC_GPU_TO_LLCC	0
#define KONA_ICC_GPU_TO_MEM	1
#define KONA_ICC_NPU_TO_LLCC	2
#define KONA_ICC_NPU_TO_MEM	3
#define KONA_ICC_CPU_TO_LLCC	4
#define KONA_ICC_CPU_TO_MEM	5
#define KONA_ICC_DISP0_TO_MEM	6
#define KONA_ICC_DISP1_TO_MEM	7
#define KONA_ICC_NPUDSP_TO_MEM	8
#define KONA_ICC_CPU0_TO_LLCC	9
#define KONA_ICC_CPU0_TO_MEM	10
#define KONA_ICC_CPU1_TO_LLCC	11
#define KONA_ICC_CPU1_TO_MEM	12
#define KONA_ICC_CPU2_TO_LLCC	13
#define KONA_ICC_CPU2_TO_MEM	14
#define KONA_ICC_CPU3_TO_LLCC	15
#define KONA_ICC_CPU3_TO_MEM	16
#define KONA_ICC_CPU4_TO_LLCC	17
#define KONA_ICC_CPU4_TO_MEM	18
#define KONA_ICC_CPU5_TO_LLCC	19
#define KONA_ICC_CPU5_TO_MEM	20
#define KONA_ICC_CPU6_TO_LLCC	21
#define KONA_ICC_CPU6_TO_MEM	22
#define KONA_ICC_CPU7_TO_LLCC	23
#define KONA_ICC_CPU7_TO_MEM	24
#define KONA_ICC_CPU_TO_PRNG	25
#define KONA_ICC_CPU_TO_GPU_CFG	26
#define KONA_ICC_GMU_TO_LLCC	27
#define KONA_ICC_GMU_TO_MEM	28
#define KONA_ICC_CAM_CFG		29
#define KONA_ICC_DISP_CFG		30
#define KONA_ICC_VIDEO_CFG		31
#define KONA_ICC_UFS_TO_LLCC	32
#define KONA_ICC_UFS_TO_MEM	33
#define KONA_ICC_USB0_TO_MEM	34
#define KONA_ICC_USB1_TO_MEM	35
#define KONA_ICC_QUP_TO_MEM	36
#define KONA_ICC_SDHC2_TO_MEM	37
#define KONA_ICC_VIDEO_TO_LLCC	38
#define KONA_ICC_VIDEO_TO_MEM	39
#define KONA_ICC_CVP_TO_MEM	40
#define KONA_ICC_PAS_TO_MEM	41
#define KONA_ICC_PCIE0_TO_MEM	42
#define KONA_ICC_PCIE1_TO_MEM	43
#define KONA_ICC_PCIE2_TO_MEM	44
#define KONA_ICC_CRYPTO_TO_MEM	45
#define KONA_ICC_TSIF_TO_MEM	46
#define KONA_ICC_IPA_TO_LLCC	47
#define KONA_ICC_IPA_TO_MEM	48
#define KONA_ICC_IPA_TO_IMEM	49
#define KONA_ICC_IPA_CFG		50
#define KONA_ICC_IPA_CORE	51
#define KONA_ICC_NUM_NODES 52
#endif
